### ISSUE TITLE
Question on SCBART baseline implementation

### ISSUE THREAD

**Issue by theaitetus** [yangjingyuan/ConstDecoder#1]
Hi 
Thanks for sharing your constdecoder code public.

Recently, I have been very excited to adopt constdecoder for various domains of the ASR datasets.

 However, I would like to compare your baseline SCBART whose implementation is not public.

It would be thankful if you could share your code for SCBART

Thanks in advance

**Comment by yangjingyuan** [comment]
Hi,

Since there may exist copyright concern, we recommend you to ask for the code from the SC_BART autuors (https://www.isca-speech.org/archive/pdfs/interspeech_2021/zhao21_interspeech.pdf), or you can replicate it by using huggingface transformers (https://huggingface.co/facebook/bart-base).
